manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dongle
      url-base: https://github.com/th4656
  projects:
    - name: zmk
      remote: dongle
      revision: main
      import: app/west.yml
  self:
    path: config
